--- CallbackQuery class wrapping an incoming callback query update.
local Message = require('bot.classes.Message')
local defineGetters = require('bot.libs.getter')
local api = require('bot.api')

--- Fields of the callback object.
-- @table callback
-- @tfield number update_id update identifier
-- @tfield table callback_query raw CallbackQuery object from the Telegram Bot API
-- @tfield ?table message raw Message object the callback button is attached to
-- @tfield boolean is_callback_query always true, distinguishes the object from a message object
-- @tfield ?table arguments named arguments parsed from the callback data,
-- set by processes.processCommand for commands with arguments_schema
-- @tfield ?string __command resolved command name, set by bot.callbackCommand
local callback = {}
callback.__index = callback

--- Create a new callback object.
-- @tparam table ctx update data with update_id and callback_query fields
-- @treturn table callback object
function callback:new(ctx)
  local obj = {}

  obj.update_id = ctx.update_id

  local t_message = Message(ctx.callback_query.message, { direct = true })

  obj.message = t_message.message
  obj.callback_query = ctx.callback_query
  obj.is_callback_query = true

  return setmetatable(obj, self)
end

--- Getters.
-- Generated by libs.getter from the mapping below. Each getter returns the value
-- at the listed path inside the object, or nil when any segment of the path is missing.
-- @section getters

defineGetters(callback, {
  --- Get the update identifier.
  -- @function callback:getUpdateId
  -- @treturn ?number update_id
  getUpdateId     = 'update_id',

  --- Get the callback query identifier.
  -- @function callback:getQueryId
  -- @treturn ?string callback_query.id
  getQueryId      = 'callback_query.id',

  --- Get the user who pressed the button.
  -- @function callback:getUserFrom
  -- @treturn ?table callback_query.from, User object
  getUserFrom     = 'callback_query.from',

  --- Get the identifier of the user who pressed the button.
  -- @function callback:getUserFromId
  -- @treturn ?number callback_query.from.id
  getUserFromId   = 'callback_query.from.id',

  --- Get the data of the pressed button.
  -- @function callback:getQueryData
  -- @treturn ?string callback_query.data
  getQueryData    = 'callback_query.data',
})

-- START DEPRECATED BLOCK

--- Deprecated.
-- Kept for backward compatibility with older library versions.
-- @section deprecated

defineGetters(callback, {
  --- Get the chat of the attached message.
  -- @function callback:getChat
  -- @treturn ?table message.chat, Chat object
  getChat              = 'message.chat',

  --- Get the chat identifier of the attached message.
  -- @function callback:getChatId
  -- @treturn ?number message.chat.id
  getChatId            = 'message.chat.id',

  --- Get the chat type of the attached message.
  -- @function callback:getChatType
  -- @treturn ?string message.chat.type
  -- @see enums.chat_type
  getChatType          = 'message.chat.type',

  --- Get the text of the attached message.
  -- @function callback:getText
  -- @treturn ?string message.text
  getText              = 'message.text',

  --- Get the identifier of the attached message.
  -- @function callback:getMessageId
  -- @treturn ?number message.message_id
  getMessageId         = 'message.message_id',

  --- Get the sender of the attached message.
  -- @function callback:getUserMessageFrom
  -- @treturn ?table message.from, User object
  getUserMessageFrom   = 'message.from',

  --- Get the author of the message the attached message replies to.
  -- @function callback:getUserReply
  -- @treturn ?table message.reply_to_message.from, User object
  getUserReply         = 'message.reply_to_message.from',

  --- Get the message the attached message replies to.
  -- @function callback:getReplyToMessage
  -- @treturn ?table message.reply_to_message, raw Message object
  getReplyToMessage    = 'message.reply_to_message',

  --- Get the inline keyboard of the attached message.
  -- @function callback:getInlineKeyboard
  -- @treturn ?table message.reply_markup.inline_keyboard, array of button rows
  getInlineKeyboard    = 'message.reply_markup.inline_keyboard',

  --- Get the sender chat of the message the attached message replies to.
  -- @function callback:getSenderChat
  -- @treturn ?table message.reply_to_message.sender_chat, Chat object
  getSenderChat        = 'message.reply_to_message.sender_chat',
})

--- Check whether the callback query sender is the message reply author.
-- @treturn ?boolean true if it is the same user, false otherwise,
-- nil when the attached message is not a reply
function callback:isSameUser()
  if self.callback_query and self.callback_query.from and
    self.message and self.message.reply_to_message
  then
    return self.callback_query.from.id == self.message.reply_to_message.from.id
  end
end

-- END DEPRECATED BLOCK

--- @section end

--- Get the associated message.
-- @treturn ?table raw Message object the callback button is attached to
function callback:getMessage()
  return self.message
end

--- Split the callback query data into arguments.
-- @tparam[opt] table opts
-- @tparam[opt=' '] string opts.separator separator used to split the data
-- @tparam[opt=10] number opts.count maximum number of arguments
-- @treturn table arguments list, the first item is the command name
-- @raise if the callback query has no data
function callback:getArguments(opts)
  opts = opts or {}

  if self.callback_query then
    local separator = opts.separator or ' '
    local count = opts.count or 10
    return self.callback_query.data:split(separator, count)
  end
end

--- Strip the leading command from the callback query data.
-- Works only after the command was resolved by bot.callbackCommand.
-- @treturn ?string data without the command, nil when there is no data or resolved command
-- @treturn ?number number of replacements made
function callback:trimCommand()
  if self.callback_query and self.callback_query.data and self.__command then
    local res, count = self.callback_query.data:gsub(self.__command..' ', '', 1)

    return res, count
  end
end

--- Send a reply to the same chat.
-- A passed table is modified: chat_id is set when missing.
-- @tparam string|table fields text string or sendMessage fields
-- @treturn[1] table response from the Telegram Bot API
-- @treturn[2] table err
-- @usage
-- ctx:reply('Hello!')
-- ctx:reply({ text = 'Hello!', reply_markup = ... })
function callback:reply(fields)
  if type(fields) == 'string' then
    fields = { text = fields }
  end

  if self.message and self.message.chat then
    fields.chat_id = fields.chat_id or self.message.chat.id
  end

  return api.call('sendMessage', fields)
end

--- Answer the callback query (shows a notification to the user).
-- A passed table is modified: callback_query_id is set when missing.
-- @tparam[opt] string|table fields text string or answerCallbackQuery fields
-- @treturn[1] table response from the Telegram Bot API
-- @treturn[2] table err
-- @usage
-- ctx:answer('Done!')
-- ctx:answer({ text = 'Error!', show_alert = true })
function callback:answer(fields)
  if type(fields) == 'string' then
    fields = {
      text = fields,
      show_alert = false,
    }
  elseif fields == nil then
    fields = {}
  end

  fields.callback_query_id = fields.callback_query_id or self:getQueryId()

  return api.call('answerCallbackQuery', fields)
end

setmetatable(callback, {
  __call = callback.new
})

return callback
