--- ChatMember class wrapping a chat_member update.
local defineGetters = require('bot.libs.getter')

local chatMember = {}
chatMember.__index = chatMember

--- Create a new chatMember object.
-- @tparam table ctx update data with update_id and chat_member fields
-- @treturn table chatMember object
function chatMember:new(ctx)
  local obj = {}
  obj.update_id = ctx.update_id
  obj.chat_member = ctx.chat_member

  return setmetatable(obj, self)
end

--- Getters.
-- Generated by libs.getter from the mapping below. Each getter returns the value
-- at the listed path inside the object, or nil when any segment of the path is missing.
-- @section getters

defineGetters(chatMember, {
  --- Get the update identifier.
  -- @function chatMember:getUpdateId
  -- @treturn ?number update_id
  getUpdateId              = 'update_id',

  --- Get the chat the change happened in.
  -- @function chatMember:getChat
  -- @treturn ?table chat_member.chat, Chat object
  getChat                  = 'chat_member.chat',

  --- Get the chat identifier.
  -- @function chatMember:getChatId
  -- @treturn ?number chat_member.chat.id
  getChatId                = 'chat_member.chat.id',

  --- Get the chat type.
  -- @function chatMember:getChatType
  -- @treturn ?string chat_member.chat.type
  -- @see enums.chat_type
  getChatType              = 'chat_member.chat.type',

  --- Get the user who performed the change.
  -- @function chatMember:getUserFrom
  -- @treturn ?table chat_member.from, User object
  getUserFrom              = 'chat_member.from',

  --- Get the identifier of the user who performed the change.
  -- @function chatMember:getUserFromId
  -- @treturn ?number chat_member.from.id
  getUserFromId            = 'chat_member.from.id',

  --- Get the date of the change.
  -- @function chatMember:getDate
  -- @treturn ?number chat_member.date, Unix time
  getDate                  = 'chat_member.date',

  --- Get the new state of the chat member.
  -- @function chatMember:getNewChatMember
  -- @treturn ?table chat_member.new_chat_member, ChatMember object
  getNewChatMember         = 'chat_member.new_chat_member',

  --- Get the previous state of the chat member.
  -- @function chatMember:getOldChatMember
  -- @treturn ?table chat_member.old_chat_member, ChatMember object
  getOldChatMember         = 'chat_member.old_chat_member',

  --- Get the previous status of the chat member.
  -- @function chatMember:getOldChatMemberStatus
  -- @treturn ?string chat_member.old_chat_member.status
  -- @see enums.chat_member_status
  getOldChatMemberStatus   = 'chat_member.old_chat_member.status',

  --- Get the new status of the chat member.
  -- @function chatMember:getNewChatMemberStatus
  -- @treturn ?string chat_member.new_chat_member.status
  -- @see enums.chat_member_status
  getNewChatMemberStatus   = 'chat_member.new_chat_member.status',
})

setmetatable(chatMember, {
  __call = chatMember.new
})

return chatMember
