--- Message class wrapping an incoming Telegram message update.
local SuccessfulPayment = require('bot.classes.SuccessfulPayment')
local defineGetters = require('bot.libs.getter')
local api = require('bot.api')

--- Fields of the message object.
-- @table message
-- @tfield ?number update_id update identifier, nil for an object created with opts.direct
-- @tfield table message raw Message object from the Telegram Bot API
-- @tfield ?table arguments named arguments, set by processes.processCommand
-- for commands with arguments_schema
-- @tfield ?string __command resolved command name, set by bot.command
local message = {}
message.__index = message

--- Create a new message object.
-- @tparam table ctx update data with update_id and message fields
-- @tparam[opt] table opts
-- @tparam[opt] boolean opts.direct treat ctx as the message itself, not an update
-- @treturn table message object
function message:new(ctx, opts)
  local obj = {}

  local update_id
  local refMessage

  if opts and opts.direct then
    refMessage = ctx
  else
    update_id = ctx.update_id
    refMessage = ctx.message
  end

  obj.update_id = update_id
  obj.message = refMessage

  if refMessage and refMessage.successful_payment then
    refMessage.successful_payment = SuccessfulPayment(refMessage.successful_payment)
  end

  return setmetatable(obj, self)
end

--- Get the message object itself.
-- @treturn table message object
function message:getMessage()
  return self
end

--- Split the message text into arguments.
-- @tparam[opt] table opts
-- @tparam[opt=' '] string opts.separator separator used to split the text
-- @tparam[opt=10] number opts.count maximum number of arguments
-- @treturn ?table arguments list, nil when the message has no text
function message:getArguments(opts)
  opts = opts or {}

  if self.message and self.message.text then
    local separator = opts.separator or ' '
    local count = opts.count or 10
    return self.message.text:split(separator, count)
  end
end

--- Getters.
-- Generated by libs.getter from the mapping below. Each getter returns the value
-- at the listed path inside the object, or nil when any segment of the path is missing.
-- @section getters

defineGetters(message, {
  --- Get the update identifier.
  -- @function message:getUpdateId
  -- @treturn ?number update_id
  getUpdateId            = 'update_id',

  --- Get the chat the message belongs to.
  -- @function message:getChat
  -- @treturn ?table message.chat, Chat object
  getChat                = 'message.chat',

  --- Get the chat identifier.
  -- @function message:getChatId
  -- @treturn ?number message.chat.id
  getChatId              = 'message.chat.id',

  --- Get the chat type.
  -- @function message:getChatType
  -- @treturn ?string message.chat.type
  -- @see enums.chat_type
  getChatType            = 'message.chat.type',

  --- Get the message identifier.
  -- @function message:getMessageId
  -- @treturn ?number message.message_id
  getMessageId           = 'message.message_id',

  --- Get the message text.
  -- @function message:getText
  -- @treturn ?string message.text
  getText                = 'message.text',

  --- Get the sender of the message.
  -- @function message:getUserFrom
  -- @treturn ?table message.from, User object
  getUserFrom            = 'message.from',

  --- Get the sender identifier.
  -- @function message:getUserFromId
  -- @treturn ?number message.from.id
  getUserFromId          = 'message.from.id',

  --- Get the author of the message being replied to.
  -- @function message:getUserReply
  -- @treturn ?table message.reply_to_message.from, User object
  getUserReply           = 'message.reply_to_message.from',

  --- Get the origin of the message replied to from another chat.
  -- @function message:getExternalReply
  -- @treturn ?table message.external_reply.origin, MessageOrigin object
  getExternalReply       = 'message.external_reply.origin',

  --- Get the identifier of the author of the message being replied to.
  -- @function message:getUserReplyId
  -- @treturn ?number message.reply_to_message.from.id
  getUserReplyId         = 'message.reply_to_message.from.id',

  --- Get the message being replied to.
  -- @function message:getReplyToMessage
  -- @treturn ?table message.reply_to_message, raw Message object
  getReplyToMessage      = 'message.reply_to_message',

  --- Get the identifier of the message being replied to.
  -- @function message:getReplyToMessageId
  -- @treturn ?number message.reply_to_message.message_id
  getReplyToMessageId    = 'message.reply_to_message.message_id',

  --- Get the entities of the message text.
  -- @function message:getEntities
  -- @treturn ?table message.entities, array of MessageEntity
  getEntities            = 'message.entities',

  --- Get the dice of the message.
  -- @function message:getDice
  -- @treturn ?table message.dice, Dice object
  getDice                = 'message.dice',

  --- Get the date the message was sent.
  -- @function message:getDate
  -- @treturn ?number message.date, Unix time
  getDate                = 'message.date',

  --- Get the chat the message was sent on behalf of.
  -- @function message:getSenderChat
  -- @treturn ?table message.sender_chat, Chat object
  getSenderChat          = 'message.sender_chat',

  --- Get the identifier of the chat the message was sent on behalf of.
  -- @function message:getSenderChatId
  -- @treturn ?number message.sender_chat.id
  getSenderChatId        = 'message.sender_chat.id',

  --- Get the successful payment of the message.
  -- @function message:getSuccessfulPayment
  -- @treturn ?table message.successful_payment, classes.SuccessfulPayment object
  -- @see classes.SuccessfulPayment
  getSuccessfulPayment   = 'message.successful_payment',
})

-- START DEPRECATED BLOCK

--- Deprecated.
-- left_chat_member and new_chat_member should be separate classes.
-- Kept for backward compatibility with older library versions.
-- @section deprecated

defineGetters(message, {
  --- Get the member removed from the chat.
  -- @function message:getLeftChatMember
  -- @treturn ?table message.left_chat_member, User object
  getLeftChatMember   = 'message.left_chat_member',

  --- Get the member added to the chat.
  -- @function message:getNewChatMember
  -- @treturn ?table message.new_chat_member, User object
  getNewChatMember    = 'message.new_chat_member',

  --- Get the members added to the chat.
  -- @function message:getNewChatMembers
  -- @treturn ?table message.new_chat_members, array of User
  getNewChatMembers   = 'message.new_chat_members',
})

--- Check whether the message sender is a new chat member.
-- @treturn ?boolean true if the sender is a new chat member, false otherwise,
-- nil when the message has no new_chat_members
function message:isNewChatMember()
  if self.message and self.message.new_chat_members then
    return self.message.new_chat_members[1].id == self.message.from.id
  end
end

--- Check whether the message sender added a new chat member.
-- @treturn ?boolean true if the sender added a new chat member, false otherwise,
-- nil when the message has no new_chat_members
function message:isAddNewChatMember()
  if self.message and self.message.new_chat_members then
    return self.message.new_chat_members[1].id ~= self.message.from.id
  end
end

--- Check whether the message sender is a left chat member.
-- @treturn ?boolean true if the sender is a left chat member, false otherwise,
-- nil when the message has no left_chat_member
function message:isLeftMember()
  if self.message and self.message.left_chat_member then
    return self.message.left_chat_member.id == self.message.from.id
  end
end

--- Check whether the message sender removed a chat member.
-- @treturn ?boolean true if the sender removed a chat member, false otherwise,
-- nil when the message has no left_chat_member
function message:isRemoveMember()
  if self.message and self.message.left_chat_member then
    return self.message.left_chat_member.id ~= self.message.from.id
  end
end

-- END DEPRECATED BLOCK

--- @section end

--- Strip the leading command from the message text.
-- Works only after the command was resolved by bot.command.
-- @treturn ?string text without the command, nil when there is no text or resolved command
-- @treturn ?number number of replacements made
function message:trimCommand()
  if self.message and self.message.text and self.__command then
    local res, count = self.message.text:gsub(self.__command..' ', '', 1)
    return res, count
  end
end

--- Send a reply to the same chat.
-- A passed table is modified: chat_id is set when missing.
-- @tparam string|table fields text string or sendMessage fields
-- @treturn[1] table response from the Telegram Bot API
-- @treturn[2] table err
-- @usage
-- ctx:reply('Hello!')
-- ctx:reply({ text = 'Hello!', reply_markup = ... })
function message:reply(fields)
  if type(fields) == 'string' then
    fields = { text = fields }
  end

  fields.chat_id = fields.chat_id or self:getChatId()

  return api.call('sendMessage', fields)
end

--- Send a reply referencing this message (reply_parameters).
-- Caller-provided fields.reply_parameters is respected (e.g. built via types.ReplyParameters).
-- A passed table is modified: chat_id and reply_parameters are set when missing.
-- @tparam string|table fields text string or sendMessage fields
-- @treturn[1] table response from the Telegram Bot API
-- @treturn[2] table err
-- @see types.ReplyParameters
-- @usage
-- ctx:replyToMessage('Hello!')
function message:replyToMessage(fields)
  if type(fields) == 'string' then
    fields = { text = fields }
  end

  fields.chat_id = fields.chat_id or self:getChatId()
  fields.reply_parameters = fields.reply_parameters or {
    message_id = self:getMessageId()
  }

  return api.call('sendMessage', fields)
end

setmetatable(message, {
  __call = message.new
})

return message
