--- MyChatMember class wrapping a my_chat_member update.
local defineGetters = require('bot.libs.getter')

--- Fields of the myChatMember object.
-- @table myChatMember
-- @tfield number update_id update identifier
-- @tfield table my_chat_member raw ChatMemberUpdated object from the Telegram Bot API
local myChatMember = {}
myChatMember.__index = myChatMember

--- Create a new myChatMember object.
-- @tparam table ctx update data with update_id and my_chat_member fields
-- @treturn table myChatMember object
function myChatMember:new(ctx)
  local obj = {}
  obj.update_id = ctx.update_id
  obj.my_chat_member = ctx.my_chat_member

  return setmetatable(obj, self)
end

--- Getters.
-- Generated by libs.getter from the mapping below. Each getter returns the value
-- at the listed path inside the object, or nil when any segment of the path is missing.
-- @section getters

defineGetters(myChatMember, {
  --- Get the update identifier.
  -- @function myChatMember:getUpdateId
  -- @treturn ?number update_id
  getUpdateId              = 'update_id',

  --- Get the chat the change happened in.
  -- @function myChatMember:getChat
  -- @treturn ?table my_chat_member.chat, Chat object
  getChat                  = 'my_chat_member.chat',

  --- Get the chat identifier.
  -- @function myChatMember:getChatId
  -- @treturn ?number my_chat_member.chat.id
  getChatId                = 'my_chat_member.chat.id',

  --- Get the chat type.
  -- @function myChatMember:getChatType
  -- @treturn ?string my_chat_member.chat.type
  -- @see enums.chat_type
  getChatType              = 'my_chat_member.chat.type',

  --- Get the user who performed the change.
  -- @function myChatMember:getUserFrom
  -- @treturn ?table my_chat_member.from, User object
  getUserFrom              = 'my_chat_member.from',

  --- Get the identifier of the user who performed the change.
  -- @function myChatMember:getUserFromId
  -- @treturn ?number my_chat_member.from.id
  getUserFromId            = 'my_chat_member.from.id',

  --- Get the date of the change.
  -- @function myChatMember:getDate
  -- @treturn ?number my_chat_member.date, Unix time
  getDate                  = 'my_chat_member.date',

  --- Get the previous state of the bot.
  -- @function myChatMember:getOldChatMember
  -- @treturn ?table my_chat_member.old_chat_member, ChatMember object
  getOldChatMember         = 'my_chat_member.old_chat_member',

  --- Get the new state of the bot.
  -- @function myChatMember:getNewChatMember
  -- @treturn ?table my_chat_member.new_chat_member, ChatMember object
  getNewChatMember         = 'my_chat_member.new_chat_member',

  --- Get the new status of the bot.
  -- @function myChatMember:getNewChatMemberStatus
  -- @treturn ?string my_chat_member.new_chat_member.status
  -- @see enums.chat_member_status
  getNewChatMemberStatus   = 'my_chat_member.new_chat_member.status',

  --- Get the previous status of the bot.
  -- @function myChatMember:getOldChatMemberStatus
  -- @treturn ?string my_chat_member.old_chat_member.status
  -- @see enums.chat_member_status
  getOldChatMemberStatus   = 'my_chat_member.old_chat_member.status',
})

setmetatable(myChatMember, {
  __call = myChatMember.new
})

return myChatMember
