--- PreCheckoutQuery class wrapping a pre_checkout_query update.
local defineGetters = require('bot.libs.getter')

local PreCheckoutQuery = {}
PreCheckoutQuery.__index = PreCheckoutQuery

--- Create a new PreCheckoutQuery object.
-- @tparam table ctx update data with update_id and pre_checkout_query fields
-- @treturn table PreCheckoutQuery object
function PreCheckoutQuery:new(ctx)
  local obj = {}
  obj.update_id = ctx.update_id
  obj.pre_checkout_query = ctx.pre_checkout_query

  return setmetatable(obj, self)
end

--- Getters.
-- Generated by libs.getter from the mapping below. Each getter returns the value
-- at the listed path inside the object, or nil when any segment of the path is missing.
-- @section getters

defineGetters(PreCheckoutQuery, {
  --- Get the update identifier.
  -- @function PreCheckoutQuery:getUpdateId
  -- @treturn ?number update_id
  getUpdateId         = 'update_id',

  --- Get the bot-specified invoice payload.
  -- @function PreCheckoutQuery:getInvoicePayload
  -- @treturn ?string pre_checkout_query.invoice_payload
  getInvoicePayload   = 'pre_checkout_query.invoice_payload',

  --- Get the unique query identifier.
  -- @function PreCheckoutQuery:getId
  -- @treturn ?string pre_checkout_query.id
  getId               = 'pre_checkout_query.id',

  --- Get the currency code.
  -- @function PreCheckoutQuery:getCurrency
  -- @treturn ?string pre_checkout_query.currency, ISO 4217 code, 'XTR' for Telegram Stars
  getCurrency         = 'pre_checkout_query.currency',

  --- Get the user who sent the query.
  -- @function PreCheckoutQuery:getUserFrom
  -- @treturn ?table pre_checkout_query.from, User object
  getUserFrom         = 'pre_checkout_query.from',

  --- Get the total price.
  -- @function PreCheckoutQuery:getTotalAmount
  -- @treturn ?number pre_checkout_query.total_amount, in the smallest currency units
  getTotalAmount      = 'pre_checkout_query.total_amount',
})

setmetatable(PreCheckoutQuery, {
  __call = PreCheckoutQuery.new
})

return PreCheckoutQuery
