--- SuccessfulPayment class wrapping a successful_payment message field.
-- @pragma nostrip
local defineGetters = require('bot.libs.getter')

local SuccessfulPayment = {}
SuccessfulPayment.__index = SuccessfulPayment

--- Create a new SuccessfulPayment object.
-- The passed table itself becomes the object: its fields stay reachable directly.
-- @tparam table successful_payment raw successful_payment data
-- @treturn table SuccessfulPayment object
function SuccessfulPayment:new(successful_payment)
  return setmetatable(successful_payment, self)
end

--- Get the SuccessfulPayment object itself.
-- @treturn table SuccessfulPayment object
function SuccessfulPayment:getSelf()
  return self
end

--- Getters.
-- Generated by libs.getter from the mapping below. Each getter returns the value
-- at the listed path inside the object, or nil when any segment of the path is missing.
-- @section getters

defineGetters(SuccessfulPayment, {
  --- Get the currency code.
  -- @function SuccessfulPayment:getCurrency
  -- @treturn ?string currency, ISO 4217 code, 'XTR' for Telegram Stars
  getCurrency                     = 'currency',

  --- Get the total price.
  -- @function SuccessfulPayment:getTotalAmount
  -- @treturn ?number total_amount, in the smallest currency units
  getTotalAmount                  = 'total_amount',

  --- Get the bot-specified invoice payload.
  -- @function SuccessfulPayment:getInvoicePayload
  -- @treturn ?string invoice_payload
  getInvoicePayload               = 'invoice_payload',

  --- Get the subscription expiration date.
  -- @function SuccessfulPayment:getSubscriptionExpirationDate
  -- @treturn ?number subscription_expiration_date, Unix time, recurring payments only
  getSubscriptionExpirationDate   = 'subscription_expiration_date',

  --- Check whether the payment is recurring.
  -- @function SuccessfulPayment:isRecurring
  -- @treturn ?boolean is_recurring
  isRecurring                     = 'is_recurring',

  --- Check whether the payment is the first recurring one.
  -- @function SuccessfulPayment:isFirstRecurring
  -- @treturn ?boolean is_first_recurring
  isFirstRecurring                = 'is_first_recurring',

  --- Get the shipping option chosen by the user.
  -- @function SuccessfulPayment:getShippingOptionId
  -- @treturn ?string shipping_option_id
  getShippingOptionId             = 'shipping_option_id',

  --- Get the order info provided by the user.
  -- @function SuccessfulPayment:getOrderInfo
  -- @treturn ?table order_info, OrderInfo object
  getOrderInfo                    = 'order_info',

  --- Get the Telegram payment identifier.
  -- @function SuccessfulPayment:getTelegramPaymentChargeId
  -- @treturn ?string telegram_payment_charge_id
  getTelegramPaymentChargeId      = 'telegram_payment_charge_id',

  --- Get the provider payment identifier.
  -- @function SuccessfulPayment:getProviderPaymentChargeId
  -- @treturn ?string provider_payment_charge_id
  getProviderPaymentChargeId      = 'provider_payment_charge_id',
})

setmetatable(SuccessfulPayment, {
  __call = SuccessfulPayment.new
})

return SuccessfulPayment
